name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: small 3x3
      id: small-3x3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: small 3x3
        setup-command: ''
        command: python main.py
        input: "[[1,2,3],[4,5,6],[7,8,9]]"
        expected-output: "[[0,1,2],[3,4,5],[6,7,8]]"
        comparison-method: regex
        timeout: 10
        max-score: 5
    - name: example
      id: example
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: example
        setup-command: ''
        command: python main.py
        input: "[[96,5,23,16,45,63],[20,106,50,27,38,15]]"
        expected-output: "[[95,4,22,15,44,62],[19,105,49,26,37,14]]"
        comparison-method: regex
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SMALL-3X3_RESULTS: "${{steps.small-3x3.outputs.result}}"
        EXAMPLE_RESULTS: "${{steps.example.outputs.result}}"
      with:
        runners: small-3x3,example
